services:
    top-api:
      image: ghcr.io/gitpswdnm/nestjs-learning-top-api/top-api-demo:develop
      container_name: top_api
      restart: always
      ports:
        - 3000:3000
      volumes:
        - ./.env:/opt/app/.env
